[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.production]
  command = "npm run build"
  publish = "out"

# For dynamic redirects and better support
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy-api"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle image optimization redirects
[[redirects]]
  from = "/_next/image*"
  to = "/_next/image/:splat"
  status = 200 