[build]
  command = "npm run build"
  publish = "out"

# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.production]
  command = "npm run build"
  publish = "out"

# For dynamic redirects and better support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle image optimization redirects
[[redirects]]
  from = "/_next/image*"
  to = "/_next/image/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept" 